#!/usr/bin/env python3
"""Regression tests for demonstrated belt_gcode_gate parser defects.

Covers M82/M83 + G92 E, first model-extrusion layer, G90/G91/G28/G92
position tracking, and R11 machine-axis gantry clearance (not Z − Y/√2).
"""
from __future__ import annotations

import sys
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "validation"))

from belt_gcode_gate import GcodeValidator  # noqa: E402

ORCA_HDR = "; generated by OrcaSlicer 2.3.2-dev\n;Belt Printer: 1\n"


def gate(body: str) -> GcodeValidator:
    v = GcodeValidator("<memory>", text=ORCA_HDR + body)
    v.parse()
    return v


class ExtrusionModeTests(unittest.TestCase):
    def test_m83_smaller_positive_e_is_extrusion_not_retract(self):
        v = gate(
            """
M83
;LAYER_CHANGE
G1 X10 Y0.3 E0.20
G1 X20 Y0.3 E0.10
G1 E-1.5 F2100
"""
        )
        self.assertEqual(v.retract_count, 1)
        self.assertEqual(v.ext_no_z, 2)

    def test_m82_g92_e_absolute_retract(self):
        v = gate(
            """
M82
G92 E0
;LAYER_CHANGE
G1 X10 Y0.3 E1.0
G1 E0.2 F2100
G1 X20 Y0.3 E1.2
"""
        )
        self.assertEqual(v.retract_count, 1)
        self.assertEqual(v.ext_no_z, 2)


class FirstModelLayerTests(unittest.TestCase):
    def test_skips_empty_and_retract_only_layer_change(self):
        v = gate(
            """
M83
G1 E15 F1000
;LAYER_CHANGE
G1 E-1.5 F2100
;LAYER_CHANGE
G1 X120.212 Y.7 Z.283 F24000
G1 X120.212 Y.3
G1 X129.788 Y.3 E.2653
"""
        )
        self.assertTrue(v.seen_model_extrusion)
        self.assertEqual(v.model_layer_count, 1)
        self.assertGreaterEqual(min(v.first_layer_y), 0.3 - 1e-6)
        self.assertLessEqual(max(v.first_layer_y), 0.7 + 1e-6)
        v.check_first_layer_y()
        r7 = [r for r in v.results if r[1] == "R7-1ST-Y"]
        self.assertEqual(r7[0][0], "OK")

    def test_start_purge_is_not_model_extrusion(self):
        v = gate(
            """
M82
G1 Y.1
G1 E15 F1000
G1 Z20 E25 F800
G92 E0
;LAYER_CHANGE
G1 X10 Y0.4 E0.2
"""
        )
        self.assertEqual(v.model_layer_count, 1)
        self.assertEqual(v.ext_no_z, 1)


class HomingAndModalTests(unittest.TestCase):
    def test_g28_then_absolute_y50_is_not_stale_z_collision(self):
        v = gate(
            """
M83
G90
;LAYER_CHANGE
G1 X10 Y0.3 Z0.283 E0.2
G1 X20 Y0.3 E0.2
; filament end gcode
; === IdeaFormer IR3 V2 Belt Printer End ===
G28
G1 Y50 F1000
"""
        )
        v.check_zmach()
        r11 = [r for r in v.results if r[1] == "R11-GANTRY"]
        self.assertEqual(r11[0][0], "OK")
        self.assertFalse(v.gantry_violations)

    def test_g91_without_known_base_is_uncertain_not_collision(self):
        v = gate(
            """
M83
G90
;LAYER_CHANGE
G1 X10 Y0.3 Z0.283 E0.2
G28 Y
G91
G1 Y-2
G1 X1 Y0 E0.2
"""
        )
        v.check_zmach()
        self.assertFalse(v.gantry_violations)
        self.assertGreater(v.unknown_pos_model_moves, 0)

    def test_g92_y_establishes_known_gantry(self):
        v = gate(
            """
M83
G90
G28
G92 Y0 Z0
;LAYER_CHANGE
G1 X10 Y0.3 E0.2
"""
        )
        self.assertEqual(v.y, 0.3)
        self.assertEqual(v.first_layer_y[-1], 0.3)


class R11MachineAxisTests(unittest.TestCase):
    def test_line92_style_approach_is_not_z_minus_y_over_sqrt2(self):
        """Y=0.7 Z=0.283 is a valid gantry approach; old formula gave −0.212."""
        v = gate(
            """
M83
G90
;LAYER_CHANGE
G1 X120.212 Y.7 Z.283 F24000
G1 X120.212 Y.3
G1 X129.788 Y.3 E.2653
"""
        )
        v.check_zmach()
        self.assertFalse(v.gantry_violations)
        self.assertEqual([r[0] for r in v.results if r[1] == "R11-GANTRY"], ["OK"])

    def test_known_negative_gantry_extrusion_fails(self):
        v = gate(
            """
M83
G90
;LAYER_CHANGE
G1 X10 Y-1.0 Z0.283 E0.2
"""
        )
        v.check_zmach()
        r11 = [r for r in v.results if r[1] == "R11-GANTRY"]
        self.assertEqual(r11[0][0], "FAIL")


class Plate1RegressionTests(unittest.TestCase):
    def test_windows_cli_plate_1(self):
        path = REPO / "validation/tests/fixtures/plate_1_windows_cli_box10.gcode"
        if not path.exists():
            self.skipTest("plate_1_windows_cli_box10.gcode fixture missing")
        v = GcodeValidator(str(path))
        fails, warns = v.validate()
        rules = {r[1]: r for r in v.results}
        self.assertNotIn("R11-ZMACH", rules)
        self.assertEqual(rules["R7-1ST-Y"][0], "OK")
        self.assertEqual(rules["R11-GANTRY"][0], "OK")
        self.assertFalse(fails)
        self.assertGreater(v.retract_count, 0)
        self.assertLess(v.retract_count, 200)
        self.assertGreater(min(v.first_layer_y), -0.01)
        self.assertLess(max(v.first_layer_y), 2.01)


if __name__ == "__main__":
    unittest.main(verbosity=2)
